ASSISTANT_NAME: $MUSIC_DB_URI
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      GROUP_SUPPORT: $GROUP_SUPPORT
      OWNER_ID: $OWNER_ID
      START_IMG_URL: $START_IMG_URL
      SESSION_NAME: $SESSION_NAME
      STRING_SESSION2: $STRING_SESSION2
      STRING_SESSION3: $STRING_SESSION3
      STRING_SESSION4: $STRING_SESSION4
      STRING_SESSION5: $STRING_SESSION5
      OWNER_NAME: $OWNER_NAME
      SUDO_USERS: $SUDO_USERS
      ALIVE_NAME: $ALIVE_NAME
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH
