version: "3.9"
services:
  worker:
    build: .
    environment:
       API_HASH: $API_HASH
       API_ID: $API_ID
       BOT_TOKEN: $BOT_TOKEN
       SUDO_USERS: $SUDO_USERS
       SESSION_NAME: $SESSION_NAME
       OWNER_NAME: $OWNER_NAME
       BOT_USERNAME: $BOT_USERNAME
       BOT_NAME: $BOT_NAME
       ASSISTANT_NAME: $ASSISTANT_NAME
       SESSION_NAME: $SESSION_NAME
       GROUP_SUPPORT: $GROUP_SUPPORT
       UPDATES_CHANNEL: $UPDATES_CHANNEL
       ALIVE_IMG: $ALIVE_IMG
